# Generated by Django 5.0.4 on 2024-04-06 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_amt',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='bill_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_details_set', to='billing.bill'),
        ),
        migrations.AlterField(
            model_name='bill_details',
            name='price',
            field=models.IntegerField(editable=False),
        ),
    ]
